// receive all bitcoin on chain!
name: Makefile CI 

on:
  push:
    branches: [ "luds" ]
  pull_request:
    branches: [ "luds" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@Thales-de-Miles

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
